name: astro-env
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - bokeh
  - sunpy
  - glymur
  - astropy
  - ffmpeg
  - jupyterlab
  - notebook
  - nose
  - bqplot
  - ipywidgets
  - nbgrader