name: astro-env
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - bokeh
  - sunpy
  - glymur
  - astropy
  - ffmpeg
  - jupyterlab
  - notebook
  - nose
  - bqplot
  - ipywidgets
  - nbgrader
  - plotly==4.7.1
  - plotly-orca==1.2.1
  - psutils
  - requests
  - nodejs
  - scikit-learn
  - scikit-image