name: astro-env
channels:
  - conda-forge
dependencies:
  - numpy=1.18.1
  - matplotlib=3.1.3
  - scipy=1.4.1
  - pandas=1.0.3
  - seaborn
  - bokeh
  - sunpy=1.1.3
  - glymur=0.9.1
  - astropy=4.0.1.post1
  - ffmpeg=4.2.2
  - jupyterlab=2.1.1
  - notebook=6.0.3